<a href="https://colab.research.google.com/github/MOHAMMEDSHAHBAAZ059/EDA-DTALE-SWEETVIZ-YDATA-/blob/main/Explorarory_Data_Analysis_part_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
pip install seaborn

Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.0.2)
Requirement already satisfied: pandas>=1.2 in /usr/local/lib/python3.12/dist-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in /usr/local/lib/python3.12/dist-packages (from seaborn) (3.10.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.1)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)

In [5]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('/content/ifood_df.csv')
df

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
0,58138.0,0,0,58,635,88,546,172,88,88,...,0,0,0,0,1,0,0,1529,1441,0
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,0,1,0,0,21,15,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,1,0,0,0,1,0,0,48,43,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,61223.0,0,1,46,709,43,182,42,118,247,...,0,0,0,0,1,0,0,1094,847,0
2201,64014.0,2,1,56,406,0,30,0,0,8,...,1,0,0,0,0,0,1,436,428,1
2202,56981.0,0,0,91,908,48,217,32,12,24,...,0,0,0,0,1,0,0,1217,1193,1
2203,69245.0,0,1,8,428,30,214,80,30,61,...,1,0,0,0,0,1,0,782,721,0
2204,52869.0,1,1,40,84,3,61,2,1,21,...,0,0,0,0,0,0,1,151,130,0

***Show Row***

In [7]:
df.mean(axis=1)

0       1685.051282
1       1251.589744
2       1959.179487
3        748.230769
4       1589.948718
           ...
2200    1722.666667
2201    1735.384615
2202    1618.435897
2203    1897.974359
2204    1442.205128
Length: 2205, dtype: float64

***Show Column***

In [8]:
df.mean(axis=0)

Income                  51622.094785
Kidhome                     0.442177
Teenhome                    0.506576
Recency                    49.009070
MntWines                  306.164626
MntFruits                  26.403175
MntMeatProducts           165.312018
MntFishProducts            37.756463
MntSweetProducts           27.128345
MntGoldProds               44.057143
NumDealsPurchases           2.318367
NumWebPurchases             4.100680
NumCatalogPurchases         2.645351
NumStorePurchases           5.823583
NumWebVisitsMonth           5.336961
AcceptedCmp3                0.073923
AcceptedCmp4                0.074376
AcceptedCmp5                0.073016
AcceptedCmp1                0.064399
AcceptedCmp2                0.013605
Complain                    0.009070
Z_CostContact               3.000000
Z_Revenue                  11.000000
Response                    0.151020
Age                        51.095692
Customer_Days            2512.718367
marital_Divorced            0.104308
marital_Married             0.387302
marital_Single              0.216327
marital_Together            0.257596
marital_Widow               0.034467
education_2n Cycle          0.089796
education_Basic             0.024490
education_Graduation        0.504762
education_Master            0.165079
education_PhD               0.215873
MntTotal                  562.764626
MntRegularProds           518.707483
AcceptedCmpOverall          0.299320
dtype: float64

In [9]:
import sys
if 'numpy' in sys.modules:
    del sys.modules['numpy']
import numpy
print(numpy.mean([1,2,3,4,numpy.nan]))

nan

/tmp/ipykernel_5754/3550929391.py:4: UserWarning: The NumPy module was reloaded (imported a second time). This can in some cases result in small but subtle issues and is discouraged.
  import numpy

***Create a list***

In [10]:
['1,2,3,4,np.nan']

['1,2,3,4,np.nan']

***Find mean of list***

In [11]:
import numpy as np
print(np.mean([1, 2, 3, 4,np.nan]))

nan

***Replacing Nan***

In [12]:
df.fillna(0)

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
0,58138.0,0,0,58,635,88,546,172,88,88,...,0,0,0,0,1,0,0,1529,1441,0
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,0,1,0,0,21,15,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,1,0,0,0,1,0,0,48,43,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,61223.0,0,1,46,709,43,182,42,118,247,...,0,0,0,0,1,0,0,1094,847,0
2201,64014.0,2,1,56,406,0,30,0,0,8,...,1,0,0,0,0,0,1,436,428,1
2202,56981.0,0,0,91,908,48,217,32,12,24,...,0,0,0,0,1,0,0,1217,1193,1
2203,69245.0,0,1,8,428,30,214,80,30,61,...,1,0,0,0,0,1,0,782,721,0
2204,52869.0,1,1,40,84,3,61,2,1,21,...,0,0,0,0,0,0,1,151,130,0

***This  Data does not have a nan value but this cammand to other data***

In [13]:
df['Kidhome'].fillna(value=np.mean(df['Kidhome']))

0       0
1       1
2       0
3       1
4       1
       ..
2200    0
2201    2
2202    0
2203    0
2204    1
Name: Kidhome, Length: 2205, dtype: int64

***show integer location***

In [14]:
df.iloc[2]

Income                  71613.0
Kidhome                     0.0
Teenhome                    0.0
Recency                    26.0
MntWines                  426.0
MntFruits                  49.0
MntMeatProducts           127.0
MntFishProducts           111.0
MntSweetProducts           21.0
MntGoldProds               42.0
NumDealsPurchases           1.0
NumWebPurchases             8.0
NumCatalogPurchases         2.0
NumStorePurchases          10.0
NumWebVisitsMonth           4.0
AcceptedCmp3                0.0
AcceptedCmp4                0.0
AcceptedCmp5                0.0
AcceptedCmp1                0.0
AcceptedCmp2                0.0
Complain                    0.0
Z_CostContact               3.0
Z_Revenue                  11.0
Response                    0.0
Age                        55.0
Customer_Days            2471.0
marital_Divorced            0.0
marital_Married             0.0
marital_Single              0.0
marital_Together            1.0
marital_Widow               0.0
education_2n Cycle          0.0
education_Basic             0.0
education_Graduation        1.0
education_Master            0.0
education_PhD               0.0
MntTotal                  734.0
MntRegularProds           692.0
AcceptedCmpOverall          0.0
Name: 2, dtype: float64

***vertical to horizontal ***

In [15]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,2195,2196,2197,2198,2199,2200,2201,2202,2203,2204
Income,58138.0,46344.0,71613.0,26646.0,58293.0,62513.0,55635.0,33454.0,30351.0,5648.0,...,24434.0,11012.0,44802.0,26816.0,34421.0,61223.0,64014.0,56981.0,69245.0,52869.0
Kidhome,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,...,2.0,1.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,1.0
Teenhome,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
Recency,58.0,38.0,26.0,26.0,94.0,16.0,34.0,32.0,19.0,68.0,...,9.0,82.0,71.0,50.0,81.0,46.0,56.0,91.0,8.0,40.0
MntWines,635.0,11.0,426.0,11.0,173.0,520.0,235.0,76.0,14.0,28.0,...,3.0,24.0,853.0,5.0,3.0,709.0,406.0,908.0,428.0,84.0
MntFruits,88.0,1.0,49.0,4.0,43.0,42.0,65.0,10.0,0.0,0.0,...,2.0,3.0,10.0,1.0,3.0,43.0,0.0,48.0,30.0,3.0
MntMeatProducts,546.0,6.0,127.0,20.0,118.0,98.0,164.0,56.0,24.0,6.0,...,8.0,26.0,143.0,6.0,7.0,182.0,30.0,217.0,214.0,61.0
MntFishProducts,172.0,2.0,111.0,10.0,46.0,0.0,50.0,3.0,3.0,1.0,...,20.0,7.0,13.0,3.0,6.0,42.0,0.0,32.0,80.0,2.0
MntSweetProducts,88.0,1.0,21.0,3.0,27.0,42.0,49.0,1.0,3.0,1.0,...,0.0,1.0,10.0,4.0,2.0,118.0,0.0,12.0,30.0,1.0
MntGoldProds,88.0,6.0,42.0,5.0,15.0,14.0,27.0,23.0,2.0,13.0,...,17.0,23.0,20.0,3.0,9.0,247.0,8.0,24.0,61.0,21.0
NumDealsPurchases,3.0,2.0,1.0,2.0,5.0,2.0,4.0,2.0,1.0,1.0,...,2.0,3.0,2.0,1.0,1.0,2.0,7.0,1.0,2.0,3.0
NumWebPurchases,8.0,1.0,8.0,2.0,5.0,6.0,7.0,4.0,3.0,1.0,...,2.0,3.0,9.0,0.0,1.0,9.0,8.0,2.0,6.0,3.0
NumCatalogPurchases,10.0,1.0,2.0,0.0,3.0,4.0,3.0,0.0,0.0,0.0,...,1.0,1.0,4.0,0.0,0.0,3.0,2.0,3.0,5.0,1.0
NumStorePurchases,4.0,2.0,10.0,4.0,6.0,10.0,7.0,4.0,2.0,0.0,...,2.0,2.0,12.0,3.0,2.0,4.0,5.0,13.0,10.0,4.0
NumWebVisitsMonth,7.0,5.0,4.0,6.0,5.0,6.0,6.0,8.0,9.0,20.0,...,7.0,9.0,8.0,4.0,7.0,5.0,7.0,6.0,3.0,7.0
AcceptedCmp3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AcceptedCmp4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
AcceptedCmp5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
AcceptedCmp1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
AcceptedCmp2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Complain,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Z_CostContact,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,...,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
Z_Revenue,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,...,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0,11.0
Response,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Age,63.0,66.0,55.0,36.0,39.0,53.0,49.0,35.0,46.0,70.0,...,48.0,36.0,50.0,34.0,46.0,53.0,74.0,39.0,64.0,66.0
Customer_Days,2822.0,2272.0,2471.0,2298.0,2320.0,2452.0,2752.0,2576.0,2547.0,2267.0,...,2201.0,2629.0,2836.0,2840.0,2522.0,2540.0,2178.0,2314.0,2315.0,2781.0
marital_Divorced,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
marital_Married,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0
marital_Single,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
marital_Together,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
marital_Widow,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
education_2n Cycle,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
education_Basic,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
education_Graduation,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,1.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
education_Master,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
education_PhD,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
MntTotal,1529.0,21.0,734.0,48.0,407.0,702.0,563.0,146.0,44.0,36.0,...,33.0,61.0,1029.0,19.0,21.0,1094.0,436.0,1217.0,782.0,151.0
MntRegularProds,1441.0,15.0,692.0,43.0,392.0,688.0,536.0,123.0,42.0,23.0,...,16.0,38.0,1009.0,16.0,12.0,847.0,428.0,1193.0,721.0,130.0
AcceptedCmpOverall,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0

***Show First Column***

In [16]:
df.T.iloc[0]

0       58138.0
1       46344.0
2       71613.0
3       26646.0
4       58293.0
         ...
2200    61223.0
2201    64014.0
2202    56981.0
2203    69245.0
2204    52869.0
Name: Income, Length: 2205, dtype: float64

***Filter the data of any column ***

In [17]:

df[(df['MntFruits']>10) & (df['MntMeatProducts']>100) & (df['MntGoldProds']<50)]

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0
6,55635.0,0,1,34,235,65,164,50,49,27,...,0,0,0,0,1,0,0,563,536,0
11,63033.0,0,0,82,194,61,480,225,112,30,...,0,0,0,0,1,0,0,1072,1042,0
14,82800.0,0,0,23,1006,22,115,59,68,45,...,0,0,0,0,0,0,1,1270,1225,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2168,57731.0,0,1,0,266,21,300,65,8,44,...,0,0,0,0,1,0,0,660,616,0
2173,61014.0,0,1,17,269,129,495,182,43,29,...,0,0,0,0,1,0,0,1118,1089,0
2177,41769.0,0,1,31,302,29,131,32,0,27,...,0,0,1,0,0,0,0,494,467,0
2180,80617.0,0,0,42,594,51,631,72,55,32,...,0,0,1,0,0,0,0,1403,1371,0
2202,56981.0,0,0,91,908,48,217,32,12,24,...,0,0,0,0,1,0,0,1217,1193,1

In [18]:
df

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
0,58138.0,0,0,58,635,88,546,172,88,88,...,0,0,0,0,1,0,0,1529,1441,0
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,0,1,0,0,21,15,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,1,0,0,0,1,0,0,48,43,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,61223.0,0,1,46,709,43,182,42,118,247,...,0,0,0,0,1,0,0,1094,847,0
2201,64014.0,2,1,56,406,0,30,0,0,8,...,1,0,0,0,0,0,1,436,428,1
2202,56981.0,0,0,91,908,48,217,32,12,24,...,0,0,0,0,1,0,0,1217,1193,1
2203,69245.0,0,1,8,428,30,214,80,30,61,...,1,0,0,0,0,1,0,782,721,0
2204,52869.0,1,1,40,84,3,61,2,1,21,...,0,0,0,0,0,0,1,151,130,0

***Detecting Outliers-converted***

In [19]:
Income = ['Income']

In [20]:
Kidhome = df['Kidhome']

In [21]:
df

,Income,Kidhome,Teenhome,Recency,MntWines,MntFruits,MntMeatProducts,MntFishProducts,MntSweetProducts,MntGoldProds,...,marital_Together,marital_Widow,education_2n Cycle,education_Basic,education_Graduation,education_Master,education_PhD,MntTotal,MntRegularProds,AcceptedCmpOverall
0,58138.0,0,0,58,635,88,546,172,88,88,...,0,0,0,0,1,0,0,1529,1441,0
1,46344.0,1,1,38,11,1,6,2,1,6,...,0,0,0,0,1,0,0,21,15,0
2,71613.0,0,0,26,426,49,127,111,21,42,...,1,0,0,0,1,0,0,734,692,0
3,26646.0,1,0,26,11,4,20,10,3,5,...,1,0,0,0,1,0,0,48,43,0
4,58293.0,1,0,94,173,43,118,46,27,15,...,0,0,0,0,0,0,1,407,392,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2200,61223.0,0,1,46,709,43,182,42,118,247,...,0,0,0,0,1,0,0,1094,847,0
2201,64014.0,2,1,56,406,0,30,0,0,8,...,1,0,0,0,0,0,1,436,428,1
2202,56981.0,0,0,91,908,48,217,32,12,24,...,0,0,0,0,1,0,0,1217,1193,1
2203,69245.0,0,1,8,428,30,214,80,30,61,...,1,0,0,0,0,1,0,782,721,0
2204,52869.0,1,1,40,84,3,61,2,1,21,...,0,0,0,0,0,0,1,151,130,0

In [22]:
import seaborn as sns
sns.boxplot(Kidhome)

RecursionError: maximum recursion depth exceeded

In [ ]:
sns.boxplot(Income)

In [ ]:
n