<a href="https://colab.research.google.com/github/MOHAMMEDSHAHBAAZ059/EDA-DTALE-SWEETVIZ-YDATA-/blob/main/Full_stack_Pythin_in_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***Exploratory Date Analysis***

In [1]:
import pandas as pd
import numpy as np

# Take Sample data from Any Where

In [5]:
df = pd.read_csv('/content/sample_data/california_housing_train.csv')

In [6]:
df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0
...,...,...,...,...,...,...,...,...,...
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [7]:
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-114.31,34.19,15.0,5612.0,1283.0,1015.0,472.0,1.4936,66900.0
1,-114.47,34.40,19.0,7650.0,1901.0,1129.0,463.0,1.8200,80100.0
2,-114.56,33.69,17.0,720.0,174.0,333.0,117.0,1.6509,85700.0
3,-114.57,33.64,14.0,1501.0,337.0,515.0,226.0,3.1917,73400.0
4,-114.57,33.57,20.0,1454.0,326.0,624.0,262.0,1.9250,65500.0

In [8]:
df.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
16995,-124.26,40.58,52.0,2217.0,394.0,907.0,369.0,2.3571,111400.0
16996,-124.27,40.69,36.0,2349.0,528.0,1194.0,465.0,2.5179,79000.0
16997,-124.30,41.84,17.0,2677.0,531.0,1244.0,456.0,3.0313,103600.0
16998,-124.30,41.80,19.0,2672.0,552.0,1298.0,478.0,1.9797,85800.0
16999,-124.35,40.54,52.0,1820.0,300.0,806.0,270.0,3.0147,94600.0

In [9]:
df.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000,17000.000000
mean,-119.562108,35.625225,28.589353,2643.664412,539.410824,1429.573941,501.221941,3.883578,207300.912353
std,2.005166,2.137340,12.586937,2179.947071,421.499452,1147.852959,384.520841,1.908157,115983.764387
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.790000,33.930000,18.000000,1462.000000,297.000000,790.000000,282.000000,2.566375,119400.000000
50%,-118.490000,34.250000,29.000000,2127.000000,434.000000,1167.000000,409.000000,3.544600,180400.000000
75%,-118.000000,37.720000,37.000000,3151.250000,648.250000,1721.000000,605.250000,4.767000,265000.000000
max,-114.310000,41.950000,52.000000,37937.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [10]:
df.shape

(17000, 9)

In [11]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

# DTALE **exploratory data analysis Python library that makes it easy for you to interactively view, analyse, and edit data contained within pandas dataframes **

In [3]:
import dtale

In [4]:
pip install --upgrade plotly

Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly) (2.18.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from plotly) (26.0)

In [2]:
!pip install dtale

Requirement already satisfied: dtale in /usr/local/lib/python3.12/dist-packages (3.22.0)
Requirement already satisfied: lz4 in /usr/local/lib/python3.12/dist-packages (from dtale) (4.4.5)
Requirement already satisfied: beautifulsoup4!=4.13.0b2 in /usr/local/lib/python3.12/dist-packages (from dtale) (4.13.5)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from dtale) (2026.2.25)
Requirement already satisfied: cycler in /usr/local/lib/python3.12/dist-packages (from dtale) (0.12.1)
Requirement already satisfied: dash in /usr/local/lib/python3.12/dist-packages (from dtale) (4.1.0)
Requirement already satisfied: dash-bootstrap-components in /usr/local/lib/python3.12/dist-packages (from dtale) (2.0.4)
Requirement already satisfied: et_xmlfile in /usr/local/lib/python3.12/dist-packages (from dtale) (2.0.0)
Requirement already satisfied: Flask in /usr/local/lib/python3.12/dist-packages (from dtale) (3.1.3)
Requirement already satisfied: Flask-Compress in /usr/local/lib/python3.12/dist-packages (from dtale) (1.24)
Requirement already satisfied: future>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from dtale) (1.0.0)
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.12/dist-packages (from dtale) (2.2.0)
Requirement already satisfied: kaleido in /usr/local/lib/python3.12/dist-packages (from dtale) (1.2.0)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from dtale) (3.10.0)
Requirement already satisfied: missingno in /usr/local/lib/python3.12/dist-packages (from dtale) (0.5.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from dtale) (3.6.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from dtale) (2.0.2)
Requirement already satisfied: openpyxl!=3.2.0b1 in /usr/local/lib/python3.12/dist-packages (from dtale) (3.1.5)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from dtale) (26.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from dtale) (2.2.2)
Requirement already satisfied: pkginfo in /usr/local/lib/python3.12/dist-packages (from dtale) (1.12.1.2)
Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from dtale) (6.6.0)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from dtale) (2.32.4)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from dtale) (1.6.1)
Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from dtale) (1.16.3)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (from dtale) (0.13.2)
Requirement already satisfied: squarify in /usr/local/lib/python3.12/dist-packages (from dtale) (0.4.4)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (from dtale) (0.14.6)
Requirement already satisfied: strsimpy in /usr/local/lib/python3.12/dist-packages (from dtale) (0.2.1)
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from dtale) (1.17.0)
Requirement already satisfied: werkzeug in /usr/local/lib/python3.12/dist-packages (from dtale) (3.1.7)
Requirement already satisfied: xarray in /usr/local/lib/python3.12/dist-packages (from dtale) (2025.12.0)
Requirement already satisfied: xlrd in /usr/local/lib/python3.12/dist-packages (from dtale) (2.0.2)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4!=4.13.0b2->dtale) (4.15.0)
Requirement already satisfied: importlib-metadata in /usr/local/lib/python3.12/dist-packages (from dash->dtale) (8.7.1)
Requirement already satisfied: retrying in /usr/local/lib/python3.12/dist-packages (from dash->dtale) (1.4.2)
Requirement already satisfied: nest-asyncio in /usr/local/lib/python3.12/dist-packages (from dash->dtale) (1.6.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from dash->dtale) (75.2.0)
Requirement already satisfied: blinker>=1.9.0 in /usr/local/lib/python3.12/dist-packages (from Flask->dtale) (1.9.0)
Requirement already satisfied: click>=8.1.3 in /usr/local/lib/python3.12/dist-packages (from Flask->dtale) (8.3.1)
Requirement already satisfied: jinja2>=3.1.2 in /usr/local/lib/python3.12/dist-packages (from Flask->dtale) (3.1.6)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from Flask->dtale) (3.0.3)
Requirement already satisfied: narwhals>=1.15.1 in /usr/local/lib/python3.12/dist-packages (from plotly->dtale) (2.18.1)
Requirement already satisfied: brotli in /usr/local/lib/python3.12/dist-packages (from Flask-Compress->dtale) (1.2.0)
Requirement already satisfied: backports.zstd in /usr/local/lib/python3.12/dist-packages (from Flask-Compress->dtale) (1.3.0)
Requirement already satisfied: choreographer>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from kaleido->dtale) (1.2.1)
Requirement already satisfied: logistro>=1.0.8 in /usr/local/lib/python3.12/dist-packages (from kaleido->dtale) (2.0.1)
Requirement already satisfied: orjson>=3.10.15 in /usr/local/lib/python3.12/dist-packages (from kaleido->dtale) (3.11.7)
Requirement already satisfied: pytest-timeout>=2.4.0 in /usr/local/lib/python3.12/dist-packages (from kaleido->dtale) (2.4.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (1.5.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->dtale) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->dtale) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->dtale) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->dtale) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->dtale) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->dtale) (2.5.0)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->dtale) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->dtale) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels->dtale) (1.0.2)
Requirement already satisfied: simplejson>=3.19.3 in /usr/local/lib/python3.12/dist-packages (from choreographer>=1.1.1->kaleido->dtale) (3.20.2)
Requirement already satisfied: pytest>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from pytest-timeout>=2.4.0->kaleido->dtale) (8.4.2)
Requirement already satisfied: zipp>=3.20 in /usr/local/lib/python3.12/dist-packages (from importlib-metadata->dash->dtale) (3.23.0)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=7.0.0->pytest-timeout>=2.4.0->kaleido->dtale) (2.20.0)

In [12]:
import dtale.app as dtale_app

dtale_app.USE_COLAB = True

dtale.show(df)

https://40000-m-s-kkb-usw3b2-2w1g1ophoqg06-b.us-west3-2.prod.colab.dev/dtale/main/1